### ISSUE TITLE
Set as current context does not set as current context

### ISSUE THREAD

**Issue by odockal** [redhat-developer/podman-desktop-sandbox-ext#102]
I tried to login to the dev sandbox and also noticed that by default, checkbox for settings this cluster as current context is enabled. Though, once I was logged in, kubecontext was not changed.

**Comment by odockal** [comment]
@dgolovin Still seeing this issue with 0.0.4. Is it suppose to be fixed as of that version or we need to wait for next?

**Comment by dgolovin** [comment]
@odockal It is not in 0.0.4, we need to cut out new release.
