### ISSUE TITLE
No README on catalog?

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/podman-desktop-sandbox-ext#125]
![Screenshot 2024-05-29 at 8 45 52 AM](https://github.com/redhat-developer/podman-desktop-sandbox-ext/assets/6422176/e763c599-5b8f-4137-aaf0-347958f473ab)

I see that the README is on this repo, but I don't think on the catalog?

**Comment by dgolovin** [comment]
@cdrage It is there

![image](https://github.com/redhat-developer/podman-desktop-sandbox-ext/assets/620330/130c9376-d372-49a6-8657-f9083b157246)

Could be an issue on podman-desktop side?

**Comment by cdrage** [comment]
> Related issue [containers/podman-desktop#7363](https://github.com/containers/podman-desktop/issues/7363)

thank you! looks like it is podman desktop side.

**Comment by dgolovin** [comment]
Resolved.
