### ISSUE TITLE
QE documentation of the Dev Sandbox Extension

### ISSUE THREAD

**Issue by odockal** [redhat-developer/podman-desktop-sandbox-ext#198]
Please check and go through Dev Sandbo functionality and make sure we have all documented for testing purposes.

**Comment by xbabalov** [comment]
I created a testing sheet for the purpose https://docs.google.com/spreadsheets/d/1myxSLWWPkRlxkUpmDSjQ_Ip8FMYKq_HgHdo3l1WCCcU/edit?usp=sharing
