### ISSUE TITLE
Generate default name for `Context name` field in `Create New ...` sandbox page

### ISSUE THREAD

**Issue by dgolovin** [redhat-developer/podman-desktop-sandbox-ext#20]
Would be good to have default value for Context name to let one go through creating workflow faster.  The template for context name could be:
* sandbox-${random-suffix}
* random-suffix can be random string or random word from word list

**Comment by dgolovin** [comment]
CC: @slemeur

**Comment by jeffmaury** [comment]
Once connected to Sandbox you can retrieve the username and then have the context being sandbox-username
