### ISSUE TITLE
No way to delete sandbox connections

### ISSUE THREAD

**Issue by deboer-tim** [redhat-developer/podman-desktop-sandbox-ext#23]
If I click Delete, the spinner goes forever and nothing happens.

**Comment by dgolovin** [comment]
Duplicate of #18.

**Comment by deboer-tim** [comment]
I saw #18, but I wasn't sure it's the same problem as that sounded expired-token-related. I had an instance that was <10min from initial login so token should have been fine, and an old instance that was invalid. If there is just a single issue blocked deletion I'm fine if you want to close this.

**Comment by dgolovin** [comment]
The implementation released to main.
