### ISSUE TITLE
Unclear guidance for new connections

### ISSUE THREAD

**Issue by deboer-tim** [redhat-developer/podman-desktop-sandbox-ext#24]
If you go to create a new sandbox connection there are two labels:
- OpenShift Developer Sandbox Context name:
- OpenShift Developer Sandbox login command from Developer Console:

First, both of these are very long and redundant for text field labels. We can remove the "OpenShift Developer Sandbox", or have it once at the top of the page if we need to include it.

Context: it's not clear what we're asking the user for here. Is it just the name? Existing Kube context?

Login command: for a new user it's not obvious how they'd find this, need to have a link to a doc or longer explanation. Even if you know what it is, it's not clear whether this is the full cli, just the token, etc.

**Comment by jeffmaury** [comment]
See #20

**Comment by dgolovin** [comment]
It is going to be addressed by using description markup support

**Comment by deboer-tim** [comment]
#20 would help, but still not clear what the field is. Using markup will help, we'll just need to spend some time making sure these are clear. 👍🏼
