### ISSUE TITLE
Can't deploy to DevSandbox, if the image is not previously hosted on a registry

### ISSUE THREAD

**Issue by slemeur** [redhat-developer/podman-desktop-sandbox-ext#39]
As a user, I should be informed that my image is currently not available on a registry (as it's a local one). 
When doing a deploy to kubernetes, I should be invited to use the internal registry of DevSanbox

**Comment by dgolovin** [comment]
Image can be deployed to OpenShift cluster (Developer Dandbox, Dedicated or Local) using public image registry (docker.io, quai.io) or internal OpenShift registry.

**Comment by dgolovin** [comment]
Depends on https://github.com/containers/podman-desktop/issues/2623.

**Comment by dgolovin** [comment]
Available from github snapshot image.
