### ISSUE TITLE
Make sure to use the proper URL for the registration

### ISSUE THREAD

**Issue by slemeur** [redhat-developer/podman-desktop-sandbox-ext#49]
The podman desktop extension is using the following URL:
https://github.com/redhat-developer/podman-desktop-sandbox-ext/blob/main/package.json#L19

While the docker desktop extension is pointing to:
https://github.com/redhat-developer/openshift-dd-ext/blob/f8c053bded9bc6c1bfac682cf4867b187e87ee76/client/src/components/devSandBoxButton.tsx#L13

Shouldn't it be consistent? As we are opening a separate browser, I do believe we should ensure to point to the URL that enables the user to also discover what's Developer Sandbox

**Comment by dgolovin** [comment]
@slemeur extension link you mentioned is URL for REST Registration service, which we are not using at the moment and can be removed.

We do have link to sandbox registration page and it is here https://github.com/redhat-developer/podman-desktop-sandbox-ext/blob/daad81f4828388751d817bd306d20678482f00ff/src/extension.ts#L98

Should we update to have it the same as link in Docker Desktop extension or should we get our own with `sc_cid` parameter

**Comment by dgolovin** [comment]
URL from package.json is not used for now. Removing that one.
Second URL should be updated to use correct `sc_cid`.

**Comment by slemeur** [comment]
We'll get our own `sc_cid`
