### ISSUE TITLE
Make sure the refererURL is set when pointing to developer sandbox URLs

### ISSUE THREAD

**Issue by slemeur** [redhat-developer/podman-desktop-sandbox-ext#50]
Make sure the refererURL is set when pointing to developer sandbox URLs

That will be the way that allows us to measure usage and adoption of the tool

**Comment by dgolovin** [comment]
Extension is not handling clicks to open links. @benoitf Is this already implemented on podman-desktop side?

**Comment by benoitf** [comment]
Yes it is implemented
