### ISSUE TITLE
Improve wording of "Context name"

### ISSUE THREAD

**Issue by slemeur** [redhat-developer/podman-desktop-sandbox-ext#52]
"Context name" is not easy to understand for somebody new.

I'd prefer something like "Context name for DevSandbox to easily find it in your Kubernetes contexts"

**Comment by jeffmaury** [comment]
My proposal would be to remove it and generate a context called sandbox-username

**Comment by dgolovin** [comment]
@slemeur I agree to some degree that for someone not familiar with k8s it is not easy to understand. The same would go to 'Kubernetes contexts' though. 

@jeffmaury as a compromise we can use @slemeur name for the field and generate default value using sandbox-username as template, but I am not sure if there is API for that in podman-desktop.

**Comment by dgolovin** [comment]
@slemeur I have updated description.
