### ISSUE TITLE
Add placeholders for the different values asked to the user

### ISSUE THREAD

**Issue by slemeur** [redhat-developer/podman-desktop-sandbox-ext#53]
Let's use placeholders for the values asked in the following screen:
<img width="1209" alt="Capture d’écran 2023-05-10 à 15 23 25" src="https://github.com/redhat-developer/podman-desktop-sandbox-ext/assets/1636769/166c5adf-562c-4ec3-a4a6-700b4bed3c52">

Context Name: "OpenShift Developer Sandbox" (must be a default value, to avoid the user to have to input a text in this field)
Login: provide an example of how the login command should be looking like

**Comment by dgolovin** [comment]
@benoitf is there a way to add placeholders for fields in `Create New...` form? I did not notice it.

**Comment by benoitf** [comment]
@dgolovin there is no placeholder but there is `default` key that will be set as default value (so it fills the input with that default value)

**Comment by dgolovin** [comment]
Depends on PRs to podman desktop above

![image](https://github.com/redhat-developer/podman-desktop-sandbox-ext/assets/620330/8f1560e3-0691-4146-8e06-9357a9004b53)
