### ISSUE TITLE
Extension not stopping cleanly?

### ISSUE THREAD

**Issue by deboer-tim** [redhat-developer/podman-desktop-sandbox-ext#55]
I uninstalled the Sandbox extension, then tried to install it again. Sandbox cycled several times trying to start before it finally did (see below). This doesn't happen with other extensions, nor if I restart Podman Desktop before trying to reinstall, so I think there's something that isn't getting cleaned up correctly on extension deactivation.

index.ts:125 main ↪️ Extension /Users/deboer/.local/share/containers/podman-desktop/plugins/ghcrioredhatdeveloperpodmandesktopsandboxext has been updated, reloading it
index.ts:125 main ↪️ Activating extension (redhat-sandbox)
index.ts:125 main ↪️ [redhat-sandbox] starting extension openshift-sandbox
index.ts:125 main ↪️ [redhat-sandbox] Configfile location /Users/deboer/.kube/config
index.ts:125 main ↪️ Activation extension (redhat-sandbox) ended
index.ts:125 main ↪️ Activating extension (redhat-sandbox)
index.ts:125 main ↪️ [redhat-sandbox] starting extension openshift-sandbox
index.ts:125 main ↪️ [redhat-sandbox] Configfile location /Users/deboer/.kube/config
index.ts:125 main ↪️ Activation extension (redhat-sandbox) ended
index.ts:125 main ↪️ Extension /Users/deboer/.local/share/containers/podman-desktop/plugins/ghcrioredhatdeveloperpodmandesktopsandboxext has been updated, reloading it
index.ts:125 main ↪️ [redhat-sandbox] deactivating extension openshift-sandbox
index.ts:125 main ↪️ [kind] kind extension is active
:5173/#/preferences/extensions:1 Uncaught (in promise) Error: no provider matching provider id 7
index.ts:125 main ↪️ Activating extension (redhat-sandbox)
index.ts:125 main ↪️ [redhat-sandbox] starting extension openshift-sandbox
index.ts:125 main ↪️ [redhat-sandbox] Configfile location /Users/deboer/.kube/config
index.ts:125 main ↪️ Activation extension (redhat-sandbox) ended
index.ts:125 main ↪️ Extension /Users/deboer/.local/share/containers/podman-desktop/plugins/ghcrioredhatdeveloperpodmandesktopsandboxext has been updated, reloading it
index.ts:125 main ↪️ [redhat-sandbox] deactivating extension openshift-sandbox
:5173/#/preferences/extensions:1 Uncaught (in promise) Error: no provider matching provider id 8
index.ts:125 main ↪️ Activating extension (redhat-sandbox)
index.ts:125 main ↪️ [redhat-sandbox] starting extension openshift-sandbox
index.ts:125 main ↪️ [redhat-sandbox] Configfile location /Users/deboer/.kube/config
index.ts:125 main ↪️ Activation extension (redhat-sandbox) ended
index.ts:125 main ↪️ Extension /Users/deboer/.local/share/containers/podman-desktop/plugins/ghcrioredhatdeveloperpodmandesktopsandboxext has been updated, reloading it
index.ts:125 main ↪️ [redhat-sandbox] deactivating extension openshift-sandbox
:5173/#/preferences/extensions:1 Uncaught (in promise) Error: no provider matching provider id 9
index.ts:125 main ↪️ Activating extension (redhat-sandbox)
index.ts:125 main ↪️ [redhat-sandbox] starting extension openshift-sandbox
index.ts:125 main ↪️ [redhat-sandbox] Configfile location /Users/deboer/.kube/config
index.ts:125 main ↪️ Activation extension (redhat-sandbox) ended
index.ts:125 main ↪️ Extension /Users/deboer/.local/share/containers/podman-desktop/plugins/ghcrioredhatdeveloperpodmandesktopsandboxext has been updated, reloading it

**Comment by dgolovin** [comment]
I assume it is not extension, because extension creates two items that could cause this:
* timer
* provider

Both being disposed on deactivation. Provider is through extension context subscriptions and timer is canceled in deactivate method.

@benoitf any hint what could be happening here?

**Comment by dgolovin** [comment]
@deboer-tim this is happening in dev mode only, because filesystem watcher call reloadExtension and extension loader call activateExtension collides. After running with PR above i don't see this problem when running podman-desktop with `yarn watch`.

**Comment by dgolovin** [comment]
The fix is released to main. Closing this issue.
