### ISSUE TITLE
Push image to DevSandbox not implemented

### ISSUE THREAD

**Issue by slemeur** [redhat-developer/podman-desktop-sandbox-ext#84]
As we do for kind, it should be possible to push it to DevSandbox

<img width="1162" alt="Capture d’écran 2023-06-19 à 11 16 39" src="https://github.com/redhat-developer/podman-desktop-sandbox-ext/assets/1636769/9b41cb84-353f-4ba0-9081-5709c24077f4">

**Comment by jeffmaury** [comment]
Duplicates of #39

**Comment by dgolovin** [comment]
This is now possible with latest release and extension installed form github shapshot image.
